services:
  # Web Service
  - type: web
    name: firstclass-perfume
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MPESA_CONSUMER_KEY
        value: 7Zus5jaGgRDF9csIAcT8THhA2aeT73gdColM6Xjyu07DGIAt
      - key: MPESA_CONSUMER_SECRET
        value: cENbJBAKXqvO7sflcN1VNy2ZLb4EaxmwGczOlaziRGNJjiK77er3LkggNEKG2xRs
      - key: MPESA_SHORTCODE
        value: "174379"
      - key: MPESA_PASSKEY
        value: bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
      - key: MPESA_ENV
        value: sandbox
    healthCheckPath: /
    
  # Static File Service (for images)
  - type: web
    name: perfume-images
    env: static
    plan: free
    buildCommand: "npm install"
    staticPublishPath: ./public
    envVars:
      - key: NODE_ENV
        value: production

databases:
  # No database needed for this simple site

version: "1"
